version: "3"
services:
  hub:
    image: selenium/hub:4.0.0-rc-2-20210930
    container_name: seleniumhub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=seleniumhub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=seleniumhub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  SeleniumDocker:
    image: samirshh9/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - hubMachine=hub
    volumes:
      - //c/Users/samir/Desktop/Artifacts:/usr/share/automation/test-output
